---
title: "Supplemental Material"
author: "Daniel Ahn"
date: "2024-03-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r figure S1}

#This code uses the same code as Fig 2in the Paper Figures RMD

pre.exceptions <- timeseriesdata %>% filter(POLICY_COHORT == "Pre-Policy") %>% group_by(PX_ID) %>% arrange(PX_ID, CANHX_BEGIN_DT) %>% filter(REC_EXCEPTION == 1) %>% 
  filter(EXCEPTION == 1) %>% mutate(type = 0) %>% dplyr::select(c("PX_ID", "ALLOCATION_SCORE", "LAB_SCORE", "type", "POLICY_COHORT", "TIME1", "TIME2")) %>% mutate(TIMELAPSED = TIME2 - TIME1)
pre.exceptions$TOTALTIME <- ave(pre.exceptions$TIMELAPSED, pre.exceptions$PX_ID, FUN=sum)
pre.exceptions <- pre.exceptions %>% mutate(WEIGHT_ALLOCATE = ALLOCATION_SCORE * (TIMELAPSED / TOTALTIME),
                                    WEIGHT_LABORATORY = LAB_SCORE * (TIMELAPSED / TOTALTIME))
pre.exceptions$AVG_ALLOCATION_SCORE <- ave(pre.exceptions$WEIGHT_ALLOCATE, pre.exceptions$PX_ID, FUN=sum)
pre.exceptions$AVG_LAB_SCORE <- ave(pre.exceptions$WEIGHT_LABORATORY, pre.exceptions$PX_ID, FUN=sum)
pre.exceptions <- pre.exceptions %>% mutate(AVG_SCORE_DIFFERENCE = AVG_ALLOCATION_SCORE - AVG_LAB_SCORE)
pre.exceptions <- pre.exceptions %>% mutate(count = n()) %>% filter(row_number() == 1)

post.exceptions <- timeseriesdata %>% filter(POLICY_COHORT == "Post-Policy") %>% group_by(PX_ID) %>% arrange(PX_ID, CANHX_BEGIN_DT) %>% filter(REC_EXCEPTION == 1) %>% 
  filter(EXCEPTION == 1) %>% mutate(type = 0) %>% dplyr::select(c("PX_ID", "ALLOCATION_SCORE", "LAB_SCORE", "type", "POLICY_COHORT", "TIME1", "TIME2")) %>% mutate(TIMELAPSED = TIME2 - TIME1)
post.exceptions$TOTALTIME <- ave(post.exceptions$TIMELAPSED, post.exceptions$PX_ID, FUN=sum)
post.exceptions <- post.exceptions %>% mutate(WEIGHT_ALLOCATE = ALLOCATION_SCORE * (TIMELAPSED / TOTALTIME),
                                    WEIGHT_LABORATORY = LAB_SCORE * (TIMELAPSED / TOTALTIME))
post.exceptions$AVG_ALLOCATION_SCORE <- ave(post.exceptions$WEIGHT_ALLOCATE, post.exceptions$PX_ID, FUN=sum)
post.exceptions$AVG_LAB_SCORE <- ave(post.exceptions$WEIGHT_LABORATORY, post.exceptions$PX_ID, FUN=sum)
post.exceptions <- post.exceptions %>% mutate(AVG_SCORE_DIFFERENCE = AVG_ALLOCATION_SCORE - AVG_LAB_SCORE)
post.exceptions <- post.exceptions %>% mutate(count = n()) %>% filter(row_number() == 1)


exceptionspolicy <- exceptions %>% filter(POLICY_COHORT != "Between")
t.test(AVG_ALLOCATION_SCORE ~ POLICY_COHORT, data = exceptionspolicy)
t.test(AVG_LAB_SCORE ~ POLICY_COHORT, data = exceptionspolicy)
t.test(AVG_SCORE_DIFFERENCE ~ POLICY_COHORT, data = exceptionspolicy)



fig2.1 <- ggplot(data = subset(fig2, POLICY_COHORT == "Pre-Policy"), aes(x = newscore)) +
  geom_histogram(aes(fill = EXCEPT_TYPE), color = "black",
                 position = "identity", bins = 35) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.position = "top",
        plot.title = element_text(size = 14)) +
  scale_fill_discrete(name = "") +
  labs(x = "MELD Score", y = "Number of Candidates") + 
  scale_x_continuous(breaks = c(0, 5, 10, 15, 20, 25, 30, 35, 40)) +
  scale_alpha_manual(values = c(1, 0.3), guide = "none") +
  guides(fill = guide_legend(nrow = 2)) +
  ggtitle("Pre-Policy") +
  guides(fill = guide_legend(nrow = 2))

fig2.1

fig2.2 <- ggplot(data = subset(fig2, POLICY_COHORT == "Post-Policy"), aes(x = newscore)) +
  geom_histogram(aes(fill = EXCEPT_TYPE), color = "black",
                 position = "identity", bins = 35) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size = 14)) +
  ylim(0, 1500) +
  scale_fill_discrete(name = "") +
  labs(x = "MELD Score", y = "Number of Candidates") + 
  scale_x_continuous(breaks = c(0, 5, 10, 15, 20, 25, 30, 35, 40)) +
  scale_alpha_manual(values = c(1, 0.3), guide = "none") +
  ggtitle("Post-Policy") +
  guides(fill = FALSE)

fig2.2

plot_grid(fig2.1, fig2.2,
          ncol = 1, nrow = 2,
          labels = c("A", "B"))

```

``` {r figure s2}

coxpostpolicy <- filter(timeseriesdata, POLICY_COHORT == "Post-Policy")
coxprepolicy <- filter(timeseriesdata, POLICY_COHORT == "Pre-Policy")

premodel1 <- coxme(Surv(TIME1, TIME2, NEW_DEATH) ~ ALLOCATION_SCORE + SCORE_DIFFERENCE + (1 | CAN_LISTING_CTR_ID), data = coxprepolicy)
tab_model(premodel1)

postmodel1 <- coxme(Surv(TIME1, TIME2, NEW_DEATH) ~ ALLOCATION_SCORE + SCORE_DIFFERENCE + (1 | CAN_LISTING_CTR_ID), data = coxpostpolicy)
tab_model(postmodel1)

plota <- plot_model(
  premodel1,
  show.values = TRUE,
  value.offset = .3,
  value.size = 6,
  ci.lvl = 95,
  p.shape = TRUE,
  wrap.title = 75,
  wrap.labels = 30,
  axis.labels = c(
    "Allocation and Laboratory MELD Score Difference",
    "Allocation MELD Score"
    
  ),
  title = "Association of Exceptions with\nPre-Transplant Mortality, Pre-Policy",
  axis.title = "Cause-Specific Hazard Ratio",
  grid.breaks = c(0.1, 1, 10)
)
plota.0 <- plota + theme_sjplot() +
  theme(text = element_text(size = 20),
        axis.text = element_text(colour = "black"))


plotb <- plot_model(
  postmodel1,
  show.values = TRUE,
  show.p = TRUE,
  value.offset = .3,
  value.size = 6,
  wrap.title = 75,
  wrap.labels = 30,
  axis.labels = c(
    "Allocation and Laboratory MELD Score Difference",
    "Allocation MELD Score"
  ),
  title = "Association of Exceptions with\nPre-Transplant Mortality, Post-Policy",
  axis.title = "Cause-Specific Hazard Ratio",
  grid.breaks = c(0.1, 1, 10)
)
plotb.0 <- plotb + theme_sjplot() +
  theme(text = element_text(size = 20),
        axis.text = element_text(colour = "black"))

plot_grid(plota.0, plotb.0,
          ncol = 2, nrow = 1,
          labels = c("A", "B"))



```


``` {r figure s3}

forfigs3 <- justexceptions %>% group_by(PX_ID) %>% arrange(CANHX_BEGIN_DT) %>% 
  filter(row_number() == 1) %>% ungroup() %>%
  mutate(removaltype = case_when(
    REMOVALTYPE == 0 | REMOVALTYPE == 2 ~ 0,
    REMOVALTYPE == 1 ~ 1))

survfit2(Surv(TIME_TO_REMOVAL, removaltype) ~ diagnosis, data = forfigs3) %>%
  ggsurvfit() + 
  coord_cartesian(xlim = c(0, 180)) +
  scale_x_continuous(breaks = c(0, 45, 90, 135, 180)) +
  scale_y_continuous(
    limits = c(0.9, 1),
    labels = scales::percent, 
    expand = c(0.01, 0)
  ) +
  xlab("Days after Listing") +
  theme_classic() +
  labs(title = "Pre-Transplant Survival Stratified by Primary Diagnosis")

survdiff(Surv(TIME_TO_REMOVAL, removaltype) ~ diagnosis, data = forfigs3)


```

``` {r figure s4}

barproportion <- df_by_region %>%
  distinct(Region, POLICY_COHORT, region_proportion) %>%
  filter(POLICY_COHORT != "Between") %>%
  mutate(Region = factor(Region, levels = c(1:11))) %>%
  ggplot() +
  geom_col(aes(x = Region, y = region_proportion, fill = POLICY_COHORT), position = position_dodge(width = 0.67), alpha = 0.9) +
  labs(fill = "Cohort", y = "Proportion of Candidates with Exception",
       title = "")

barproportion

```

``` {r table s5}

exceptionsmodel <- coxme(Surv(TIME1, TIME2, NEW_DEATH) ~ SCORE_DIFFERENCE + diagnosis + (1 | CAN_LISTING_CTR_ID), data = justexceptions)
tab_model(exceptionsmodel)

```

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
